### ISSUE TITLE
Version 2.4.1 fails

### ISSUE THREAD

**Issue by springcomp** [calvinmetcalf/copyfiles#109]
This is a duplicate of issue #100 which has been closed.

Environment: Windows
NodeJS: 14.7.1
copyfiles: 2.4.1

Error:

```
> npx copyfiles
  outDir = outDir.startsWith('~') ? untildify(outDir) : outDir;
                  ^

TypeError: Cannot read property 'startsWith' of undefined
    at copyFiles (C:\Projects\springcomp\yo\yeoman-custom-generator\generator-sample\node_modules\copyfiles\index.js:93:19)
    at Object.<anonymous> (C:\Projects\springcomp\yo\yeoman-custom-generator\generator-sample\node_modules\copyfiles\copyfiles:40:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

As suggested in the #100, this is the output of `console.log(argv)` on [copyfiles](https://github.com/calvinmetcalf/copyfiles/blob/db5dcfc47fbcb9d61d9349da0452498c3d6770d9/copyfiles#L40).

```
{ _: [], '$0': 'node_modules\\copyfiles\\copyfiles' }
```

**Comment by springcomp** [comment]
Also, the help screen is truncated:

```
> npx copyfiles --help
Options :
      --help     Affiche l'aide                                        [boolean]
      --version  Affiche le numéro de version                          [boolean]
  -u, --up       slice a path off the bottom of the paths               [number]
```

**Comment by vhrytsai** [comment]
This error is still reproducible on -
node - 20.3.1
copyfiles - 2.4.1
pnpm - 8.15.3

**Comment by ingridskard** [comment]
Hey, I'm getting this issue withn pnpm, however yarn is able to run this:

`copyfiles -a --verbose "./.next/static/**/*" "./.next/standalone/.next/static/"`

Using pnpm `outDir` is undefined.

**Comment by springcomp** [comment]
@ingridskard I tried [re-implementing this](https://github.com/springcomp/typescript-copyfiles) using more modern NodeJS builtin primitives like [`ReadableStream`](https://nodejs.org/api/stream.html) in TypeScript. I think the result is quite nice.

You can test the [`@springcomp/typescript-copyfiles`](https://www.npmjs.com/package/@springcomp/typescript-copyfiles) package from NPM.
